parser: "@babel/eslint-parser" # for top-level-await only, until eslint supports it natively
env:
  es2021: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  requireConfigFile: false
rules:
  quotes: [error, double]
ignorePatterns:
  - www-js/**/*.js