parser: "@babel/eslint-parser" # for top-level-await only, until eslint supports it natively
env:
  es2021: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  requireConfigFile: false
rules:
  quotes: [error, double]
ignorePatterns:
  - www-js/**/*.js
  - src/mod/supported-mods/**/*.js
  - src/mod/vanilla-patches/**/*.js
  - pbr.js
overrides:
  - files: "src/mod/**/*.[tj]s"
    rules:
      no-undef: 0