export const patchGTPOmoriFixes = () => {
  Yanfly.BEC.BattleManager_processTurn = function() {
		var subject = this._subject;
		var action = subject.currentAction();
		if (action) {
			action.prepare();
			if (action.isValid()) {
				this.startAction();
			}
			else {
				//===================================
				// Addon for checking JUICE
				if(DataManager.isSkill(action.item())) {
					if(subject.mp < action.item().mpCost) {
						this._logWindow.push("addText", subject.name().toUpperCase() + " hat nicht genug SAFT!");
						this._logWindow.push("wait");
					}
				}		
				//===================================
			}
			subject.removeCurrentAction();
		} else {
			subject.onAllActionsEnd();
			this.refreshStatus();
			this._logWindow.displayAutoAffectedStatus(subject);
			this._logWindow.displayCurrentState(subject);
			this._logWindow.displayRegeneration(subject);
			this._subject = this.getNextSubject();
		}
	}

  Gamefall.JPWordWrap.Print_Something_Txt = function() {
		const path = require("path");
		const fs = require("fs")
		const os = require("os");
		var base = path.dirname(process.mainModule.filename);
		var deskDir = `${base}`;
		fs.writeFileSync(deskDir + `___für_${$gameActors.actor(8).name()}___.txt`, `............. ...   ............................... ..... ............. ..... ..
		...........           .    ..       .   . .. ...    .  ..     .. ...    .  ..   
		...........   ..     .     .  .    OOZZZZZO    .    ..  ...  ...   .    ..  ... 
		...........                .. .OZZZZZZZZZZZZZO,     .   .     ..  ..    .   .   
		............. ..  . .  .    ZZZZZZZZZZZZZZZZZZZZO.... ... ... ... ... ... ... ..
		............. ...   ... ?ZZZZZZZZZZZZZZZZZZZZZZZMMZO......  ........ .........  
		....................  MZZZZZZZZZZZZZZZZZZZZZZZZZZZMZZZ .........................
		.....  .  .........MMMZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ........................
		   . .    ....... OZZMMZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ$......................
		   . .    .......ZZZOMMMMMMMMMZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ ....................
		 . . .    ......NZZMNMMMMMMMMMMNNZZMMMNMOMMOM8ZZZZZZZZZZZZZZI...................
		 .   . . ......OMZZZMMMMMMMMMMMMMZZZMMMMMMZZMZZZZZZZZZZZZZZZZ...................
		.. ... .. ....MZZZOMMMMMMMMMMMMMMZNMMMMMMMZMMZZZZZZZZZZZZZZZZZ, ................
		.............MMZMZZZZMMMMZMMMMMMMMMMZZMMMMMZZZZZZZZMZZMOZZZMMZZ~................
		   ..   . ..=MMZMMMZMZZMZOMMMMMMMMMMMMMMMMZZZZZZZZZZZZMOZMMMMZZZ................
		............MOMZNOOOMMMMZZDONMMMMMMMMMMMOOZZMDZOZOMOZZNNNMMMMMMOZ~..............
			. . . .ZMMMZZZZMZZZMMMDMMMMMMMMMMMMMMZZZZZMDOZMZOMMMZMOMZMZZZZ .............
		 .  ..  . MZMMZZZMZZZOZOZZZMOMMMMMMMMMZZZMMMMZZ8MMMMMMZZMZZMZMMZZZZ.............
		..........ZMZZOZOZZZMZZMZZDONMMMMMMMMM.,OMMMZZMMMMMMMMMMMMMMMMMMMZZ ............
		 .  .    ZMOMZOMOMMMMZZMMZDOMOOMMMOMM=.. ,MMMMMMMMMMMZMMMZMMMMMMMMZI............
		.. ...  ZOMMMMMMMMMMMMZOZMDO8ZMMOMMMZ.....MMMMMMMMMMMMMMMMMMMMMMMMOZ............
		........ZZMMZMMMMMMZZMMZZMMMMZMMMMMM,. ...IMMMMMMMMMMMMMMMMMMMMMMMMZ$...........
		.......8ZZMMMMMMMOMMZZMMZZZZZMMMMMM7.......IMMMMMMMMMMMMMMMMMMMMMMMOZ...........
		. .... O8DMMDDDZZMMOODOZZZDZDDDZMD~.........MMMMMMMMMMMMMMMMMMMMMMMMD...........
		 .  ..MMZOMMMOMZZMMZZMMZZOZZMMMZMZ:.........,MMMMMMMMMMMMMMMMMMMMMMMMO .........
		..... MNZZZZZMMZZMOZZZZZZZDZZZZMZM. .........OMMMMMMMMMMMMMMMMMMMMMMOM .........
		......MNZZZZZZZZZ8NZZZZNZZ8ZZZNM8~. .........~MMMMMMMM8M8ZMMMMMMMMMMM8 .........
		.....MMNZZZZZZZZMZMOMMONOMMZOMZZ..............~MMMMMMZMOMMZMMZMZOMMMMMZ.........
		....IMMMDDZZZZDZDDMZDMMMMMNDDMOZ...............=MMDDZMDZ8DOZZZZZZZDMDMM ........
		....MMMZZMZZZZMMMMMMMMMOMZMMMZM:.............. =ZMMMZMZZZZZZZZZZZZZMZZM:........
		....MMMMOZMMZMMZZMMMMMMMMMMMMOZ.................IMMMMMOZZZZZZZZZZZZZZZZM........
		...MMMNOON8MMNMMMMMMMMMMMMMMMM...................ZMZO88ZNZZZZZZZZZZZZNMN8.......
		...MMZMNZZMMMMMMMMMMMMMMMMMMMM. ................,+MZZMMMZMOZZMOZZZZOZZZZO.......
		...MMZMNOMMMMMMMMMMMMMMMMMMMMZ. ..................MMZMZMZZMMMZMOZZDZZZZZM.......
		.. MMMMMMMMMMMMMMMMMMMMMMMMMM. ...................MMMMMMMMMMMMMMMZDZZZZZZ+......
		..MMMMMMMMMMMMMMMMMMMMMMMMMMM................... .=MMMMMMMMMMMMMMODMMMZZZO .....
		..MMMMMMMMMMMMMMMMMMMMMMMMMMN. ...... ~+..........,MMOZMMZMMMMMMMMMMNMOZZZ,.....
		. MMMMMMMMMMMMMMMMMMMMMMMMMMN. ...,ZMETWASMM,...... MMMMMMOZMMMMMMMMMMMMZMO.....
		. MMMMMMMMMMMMMMMMMMMMMMMMMMD, ...NMMMISTMMMM.......MZMMMMZMMMMMMMMMMMMMMMM.....
		.MMMMMMMMMMMMMMMMMMMMMMMMMMMD ....MMHINTERMMM,......M8MDMMNMMMMMMMMMMMMMMMM.....
		. MMMMMMMMMMMMMMMMMMMMMMMMMMD.....MMMMDIRMMMM .... .ZZMZOMMMMMMMMMMMMMMMMMM.....
		. MMMMMMMMMMMMMMMMMMMMMMMMMMM.....:MMMMMMMMM.......MZOMOMZMOMMMMMMMMMMMMMMM.....
		. MMMMMMMMMMMMMMMMMMMMMMMMMMMI......=?MMMM.........MMMZMMMOZMZMMMMMMMMMMZZZ.....
		.,MMMMMMMMMMMMMMMMMMMMMMMMMMMM.....................MMMMMMMMMZZMOMMMMMMMMMMO.....
		.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM....................+MMMMMMMMMDZMD8MDDMMMMMMD.....
		.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.................. .MMMMMMMMMMZMMMMMDMNMMMMZZ.....
		.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.................. .MMMMMMMMMMMMMMMMMMOMMMZZZM....
		.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM, .... ............ZMMMMMMMMMMMMMMMMMMMMMMMZMM....
		 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ,.................MMMMMMMMMMMMMMMMMDMMMMMZOMM....
		.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.................ZMMMMMMMMMMMMMMMMMMMMMMMMMOM....
		. MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...............:MMMMMMMMMMMMMMMMMMMMMMMMMZZZ....
		..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...............+MMMMMMMMMMMMMMMMMMMMMMMMZZZZ....
		..MMMMMMMMMMMMMOMMZMMMMMMMMMMMMM .............=MMMMMMMMMMMMMMMMMMMMMMMMMZZZZ....
		..MMMMMMMMMMMMMMZZMMMMMMMMMMMMMMZ,.......... OMMMMMMMMMMMMMMMMMMMMMMZMMZZZZZ....
		.. MMMMMMMMMMMMOOZMMMMMMMMMMMMMMMZ: .........MMMMMMMMMMMMMMMMMMMMMMMOMMMZZZZI...
		.. MMNMM8MMNODZZO8MMMMMMMMMMMMMMMMZ:........MMMMMMMMMM8MMMMMMMMMNMM88ZM8ZZZZ+...
		.. MMMZ8MZZZMZZZZMMMMMMMMMMMMMMMMMMZ.......IMMMMMMMMMMMMMMMMMMMOMMDMZZZZZZZZZ...
		..MMMMMMM$OOZZZZOMMMMMMMMMMMMMMMMMMM.... .OMMMMMMMMMMMMMMMMMMMMMMZZOZZZZZZZZZ...
		..MMMMZNOZZZZZZZZMZZMMMMMMMMMMMMMMMM=. ..=MMMMMMMMMMMMMMMMMMNMZZZMZZZZZMMZZZZ...
		..MMMMM8ZZZZZZZZMMMMMMMMMMMMMMMMMMMMMM .IMMMMMMMMMMMMMMMZMMMMMMZZMDMZOZMZZZZZ...
		..MMMMMNNNZZZZZN8ZDMMMMMMMMMMMMMMMMMMM..MMMMMMMMMMMMMMMM8MMDMNZMMNMM88ZZZZZZZ...
		..MMMMMMMMZZZZZZMZMMMMMMMMMMMMMMMMMMMMZZMMMMMMMMMMMMMMMMMZZMMMOMMMMMZMMZZZZZZ ..
		..MMMMMMMZZMZZZMZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOMMMMMMMMMMZMZZZZ ..
		...MMMMMMMZMOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZMMMMMMMDMMOOMMMMZZ ..
		...MMMMMZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZMMZMZZ ..
		...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZMMMMMMMMMMMMMMMMMMMMMMMMZZ ..
		...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...
		...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZMMMMMMMMMMMMMMMMMMMMMMM...
		...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM ..
		....MMMMMMMMMMMMMMMOZOMMMMMMOMZZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...
		....MMMMMMMMMMMZMMMMMMMMMMMMMMZMMMMMMMMMMMMMMMMMMMMMMMMMMZMMMMMMMMMMMMMMMMMMM...
		....MMMMMMMMMMMMMMMMMMMZZZDZOMZZMZZZZZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...
		....MMMMMMMMMMMMMMMMMMMMMMMMNOZZZZZZZZZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...
		....MMMMMMMMMMMMMMMMMMMMMMMZMOZZZZZZZZZZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7...
		....MMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZZZZZZOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7...
		....DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZZZZMMMMMNZZZMMMMMMMMMMMMMMMMMMMMMMMMZ....
		....DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZZZZZZMMM8MZZZZZZMMMMMMMMMMMMMMMMMMMMZ....
		.... MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZZZZZDMMMZZZZZZMMMMMMMMMMZMOMMMMMMMM....
		.....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZZZZMMMMMZZZZZMMMMMMMMMMMMMOMMMMMMM....
		.... MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZZMZ8ONOZZZZMMMMMMMMMMMMMMOMMMMMM....
		.....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZMZZOZZZZZZM=...,MMMMMMMMMMMMMMM....
		..... MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ8ZOZZZZZZ. .....MMMMMMMOMMMMMMM....
		......MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZMMOZZZZZZZM .......MZOMMMMMMMMMMM....
		......MMMMMMMMMMM. ..... MMMMMMMMMMMMMMMMMMMMZZZZZZZZ..........MMMMMMMMMMMMM....
		......MMMZMMMMMM..........MMMMMMMMMMMMMMMMMMMMZZZZZZM..........NMMMMMMMMMMMM....
		......MMZMZMMMM=...... . ..MMMMMMMMMMMMMMMMMMDODZMMM.. .. ......MMMMMMMMMMMM. ..
		......MMZ$ZMMMM............MMMMMMMMMMMMMMMMMMNMMONM,............NMMMMMMMMMMO....
		.......MMOMZZOM,...... ....+MMMMMMMMMMMMMMMMMMMNMNM ............ MMMMMMMMM8Z....
		.......MZZZOZMO....... .....MMMMMMMMMMMMZMMMMMMMMMM..............MMMMMMMMMMM....
		.......MZOZZZZ .............MMMMMMMMMMMMMMZZMMMMMM.... ...........MMMMMMMMNO....
		.......NZMZZOM .............MMMMMMMMMMMMMMMMMMMMMM................MMMMMMMZO+....
		.......ZZZMZZZ ... .   .... MMMMMMMMMMMMMMMMMMMMM .... ......... .7MMMMMMOM+....
		.......MMZMZZN..............:MMMMMMMMMMMMMMMMMMMM,................ MMMMMOMN?....
		.......MMOOMM................MMMMMMMMMMMMMMMMMMMM .................MMMMMMZM+....
		........OMZMM ........ ..... MMMMMMMMMMMMMMMMMMMM ..................MMMMMZN+....
		........MMMMM...............:MMMMMMMMMMMMMMMMMMM. ..................MMMMMMM+....
		........MMMMM............... MMMMMMMMMMMMMMMMMMM. .... .............:MMMMMM+....
		........MMMMM... ..... . ....MMMMMMMMMMMMMMMMMMM. .... ......... ... MMMMMM ....
		........NMMM ................MMMMMMMMMMMMMMMMMM....... ..............MMMMMO.....
		.........MZO ......... . ....MMMMMMMMMMMMMMMMMM . ............. . .. MMMMMO.....
		........,O8M.......... ......MMMMMMMMMMMMMMMMMM ..................... MMMM:.....
		.........ZMM................ MMMMMMMMMMMMMMZM8M.......................$MMM .....
		........ MM... ............. MMMMMMMMMMMMMMMZNM.. ...................  MMZ......
		........ MM..... ..... .... .MMMMMMMMMMMMMMMMMM.. .... ......... .. . .MMM .....
		........ MM .......... ......MMMMMMMMMMMMMMMMM?.. .... .............. . MM .....
		........ 8M........... . .. .MMMMMMMMMMMMMMMMM. . .... .. ......... . ..M. .. ..
		........ ZM... ..............MMMMMMMMMMMMMMMMM .. ................... ..M ......
		.........Z ........... .... .NMMMMMMMMMMMMMMMM... ... ..... ..... ... ......... 
		.......... ........... ...... MMMMMMMMMMMMMMMM... ................... ..........
		............................. MMMMMMMMMMMMMMMM... ................... ..........
		............................. MMMMMMMMMMMMMMM+... ................... ..........
		............................. MMMMMMMMMMMMMMM...................................
		...................... .. ... MMMMMMMMMMMMMMM.... .... ......... .... .... .....
		............................. MMMMMMMMMMMMMMM.... .... ......... .... .... .....
		............................. MMMMMMMMMMMMMM:.... ................... ..........
		............................. MMMMMMMMMMMMMM..... ................... ..........
		............................. MMMMMMMMMMMMMM..... ................... ..........
		...................... ...... MMMMMMMMMMMMMM .... .............. .... ..........
		..................... ....... MMMMMMMMMMMMZ  .... .... ......... .... .... .....
		............................. MMMMOMMMMMMOM ..... ................... ..........
		..............................MMMMOMMMMMZMM. .... .... ......... .... .... .....
		..............................MMMMD8DD8OZZZ ..... .... .............. .... .....
		...............................MMMOZMMZZZZZ...... .... .............. .... .....
		...............................MMMMMZMZZZZZ ....................................
		..... ... ............ ....... MMZZMZZZZZZZ  .... .... ......... .... .... .....
		..............................$MZZZOOZZZZZZ...... ................... ..........
		...................... ....... ZZZOZZZZZZZ....... .... .............. .... .....
		 ........ .....................MZZOZZZZZZZ....... ................... ..........
		...................... ........MZOOZZZZZZZ....... ................... ..........
		.....................  ........MM88ZOZNZZZ ...... .... .............. .... .....
		..  . ... .....................MMMZMMMMZZZO...... ................... ..........
		...............................MMMMOMMZ$ZM.. .... .... ......... .... .... .....
		...............................MMM8ZNMDMMD......................................
		..  ... . ............ .........MMMMMMMMMO . .... .... ......... .... .... .....
		................................MMMMMMMZ8M......................................
		.....................  ........ MMNMMMMZM. ...... .... .............. .... .....
		...................... .. ......MMMMMMMMZ. . .... .... ......... .... .... .....
		................................MMMDMMMMD ......................................
		................................MMMZMMOMM........ ............ ...... ..........
		...................... .. ...... MOOMZMM . . .... .... ......... .... .... .....
		...................... .... .....MMMMMMM.. ...... ................... ..........
		.................................MMMMZMM......... ................... ..........
		.................................MMMMZM ......... ................... ..........
		.................................MMMZOM ......... ................... ..........
		.................................MMMOMM  ... .... .... ......... .... .... .....
		...................... .. . .....MNZZZ$... ...... ............ ...... ..........
		................................ MMMMZ:.........................................
		..................... ..... ...  MMMZM... ... ... ............... ... ..........
		...................... ..........,MMMM.... ...... ................... ..........
		...................... .......... MMZM.... ...... ................... ..........
		..................... ..... ... ..MMM ... .. .... .............. .... ..........
		..................................MMM ........... ................... ..........
		........................... ......MMM....... .... .... ......... .... .... .....
		..................................MMM............ ................... ..........
		...................... .. ... ... MM ..... . .... .... ......... .... .... .....
		.....................  .... ... ..MM ....  ...... .... .............. .... .....
		..................................DM............. ................... ..........
		....... . .........................=............. ................... ..........
		...................................+............. ................... ..........
		......... ...........  ........ .... ....  . .... .... ......... .... .... .....
		................................................................................
		.. .. . . ............ ........ .... ..... ...... .... .............. .... .....
		`)	
	}

  Gamefall.JPWordWrap.parseNoEffectEmotion = function(tname, em) {
		if(em.toLowerCase().contains("ängstlich")) { // TODO Testen!!
		  return target.name() + " kann nicht ÄNGSTLICHER werden!\r\n";
		}
		let finalString = `${tname} kann nicht ${em} werden`;
		if(finalString.length >= 40) {
		  let voinIndex = 0;
		  for(let i = 40; i >= 0; i--) {
			if(finalString[i] === " ") {
			  voinIndex = i;
			  break;
			}
		  }
		  finalString = [finalString.slice(0, voinIndex).trim(), "\r\n", finalString.slice(voinIndex).trimLeft()].join('')
		}
		return finalString;
  }

	Yanfly.BEC.Window_BattleLog_displayAddedStates = function(target) {
		target.result().addedStateObjects().forEach(function(state) {
			var stateMsg = target.isActor() ? state.message1 : state.message2;
			if (state.id === target.deathStateId()) {
				this.push('performCollapse', target);
			}
			if(state.id === target.deathStateId() && target.isActor()) {
				if([1,8,9,10,11].contains(target.actorId())) {
					stateMsg = " wurde ohnmächtig!";
				}
			}
			if (stateMsg) {
				this.push('popBaseLine');
				this.push('pushBaseLine');
				this.push('addText', target.name() + stateMsg);
				this.push('waitForEffect');
			}
		}, this);		
	}

  Permanent_Manager.save = function() {
    const pp = require("path");
    const fs = require("fs");
    const data_folder = this.dataFolder();
    const omori_folder = this.determineOmoriFolder();
    const folder = pp.join(data_folder, omori_folder);
    fs.stat(folder, (err, stat) => {
      if(!stat || !!err) {fs.mkdirSync(folder);}
      let data = JSON.stringify(this._cutsceneData);
      fs.writeFile(folder + "CUTSCENE.json", data, err => {
        if(!!err) {
          console.error("Ein Fehler ist beim Speicherprozess der Permanentdaten aufgetreten!");
          throw new Error(err);
        }
      })	
    })			
  }

  Permanent_Manager._deletePermanentCutscenes = function() {
    const pp = require("path");
    const fs = require("fs");
    const data_folder = this.dataFolder();
    const folder = pp.join(data_folder, this.determineOmoriFolder());
    fs.unlink(folder + "CUTSCENE.json", err => {
      if(!!err) {
        console.error("CUTSCENE.json kann nicht gelöscht werden!");
        throw new Error(err);
      }
      else {
        this._cutsceneData = {};
        console.info("CUTSCENE.json wurde korrekt gelöscht.")
      }
    })			
  }

	Graphics._makeFullErrorHtml = (name, message, stack) => {
    let text = ""
    if (message === "Steam wurde nicht erkannt." || message === "Dieses Spiel funktioniert nicht im SDK Modus.") {
      name = ""
      stack = [stack[1], ""]
    }
    for (let i = 2; i < stack.length; ++i) {
      text += "<font color=white>" + stack[i] + "</font><br>"
    }
    return ("<font color=\"white\"><b>" + stack[0] + "</b></font><br>" +
      "<font color=\"white\"><b>" + stack[1] + "</b></font><br>" + text)
  }

	Graphics.openSteamBugPage = () => {
    window.nw.Shell.openExternal("https://discord.gg/nYpzUDj2Bw")
  }


	Graphics.processErrorStackMessage = (stack) => {
    const data = stack.split(/(?:\r\n|\r|\n)/)
    data.unshift("OMORI ist auf einen Fehler gestoßen. Bitte melde ihn auf dem <a href=\"#\" onclick=\"Graphics.openSteamBugPage()\" style=\"color:green;\">Discord des Übersetzungsteams</a><br/>")

    for (let i = 1; i < data.length; ++i) {
      data[i] = data[i].replace(/[(](.*[/])/, "(")
    }
    return data
  }

	ysp.VideoPlayer.hasVideoFinished = function (id) {
    const video = this.getVideoById(id)
    if (!video) {
      console.warning("Scheinbar wurde das Video der ID \"" + String(id) + "\" nicht abgespielt. Die Methode wird TRUE zurückgeben")
      return true
    }
    const source = video.texture.baseTexture.source
    return source.currentTime >= source.duration
  }

	DataManager.loadGameWithoutRescue = function (savefileId) {
    this.loadGlobalInfo()
    if (this.isThisGameFile(savefileId)) {
      const json = StorageManager.load(savefileId)
      if (!json) {
        throw new Error("Der Inhalt deiner Speicherdatei wurde verändert oder sie wurde korrupt")
      }
      this.createGameObjects()
      this.extractSaveContents(JsonEx.parse(json))
      this._lastAccessedId = savefileId
      return true
    } else {
      return false
    }
  }

	Yanfly.UCE.DataManager_loadGame = function (savefileId) {
    try {
      return this.loadGameWithoutRescue(savefileId)
    } catch (e) {
      if (Utils.isOptionValid("test")) {
        console.error(e)
      } else {
        alert("Problem beim Laden - " + e)
      }
      return false
    }
  }
}