# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build mod
on: workflow_dispatch
jobs:
  Build-Mod-ZIP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install

      - name: Create tag
        uses: anothrNick/github-tag-action@1.35.0
        id: tag
        env:
          WITH_V: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build -- --git-tag ${{ steps.tag.outputs.tag }}
      
      - name: Rename artifact
        run: mv "omori-german.zip" "omori-german-${{ steps.tag.outputs.tag }}.zip"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          prerelease: true
          tag: ${{ steps.tag.outputs.tag }}
          artifacts: omori-german-${{ steps.tag.outputs.tag}}.zip
          artifactErrorsFailBuild: true
          name: OMORI German Translation ${{ steps.tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
